#Highly divisible triangular number
#Problem 12 
#The sequence of triangle numbers is generated by adding the natural numbers. 
#So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

def num_of_divisor(num):
    result = 0
    for i in range(1, num + 1):
        if num % i == 0:
            result += 1
    return result

natural_num = 1
tri_num = 1
while num_of_divisor(tri_num) <= 500:
    natural_num += 1
    tri_num += natural_num

print(tri_num)

